# Site settings
title: Redshift Logistics
email: contact@redshiftlogistics.online
url: https://redshiftlogistics.online/index.html
description: "Redshift Logistics is an independant corporation founded in 3270. We provide an array of services for clients whilst running our own operations."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#D5205E'

# Images
images:
  icon: 'https://cdn.discordapp.com/attachments/560450942554865666/598883706328842240/50fca4be-23d8-4ff9-809a-9e3b88ddc66e.png'
  header: 'https://cdn.discordapp.com/attachments/565682402878554112/588462328555765780/image1.png'
  logistics: ''
  mining: 'https://cdn.discordapp.com/attachments/565682402878554112/567267349368143872/IMG_de327035-3cec-4019-9c41-003377af0c3a.png'
  security: ''
  join-us: 'https://cdn.discordapp.com/attachments/565682402878554112/588401080581226517/IMG_cdd4afe4-95df-4bb2-b072-368b5713a55b.png'
  about-us: ''
  contact-us: 'https://cdn.discordapp.com/attachments/565682402878554112/588412010539122700/IMG_20925bf0-dc4b-4bbd-b20a-c722567379b8.png'

# Footer settings
footer: Redshift Logistics

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/rlog_elite
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
