# site settings
title: Redshift
subtitle: Logistics
email: contact@redshiftlogistics.online
description: Providing services to our customers since 3272, <br /> based out of the center of the bubble.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://redshiftlogistics.online # the base hostname & protocol for your site
author: Redshift Logistics
street_address: Unit 11 Deck 24
city: Dobrovolskiy Enterprise
state: WISE 1506+7027
zip_code:
country:
#phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: 
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
  style: compressed
