# Site settings
title: Redshift Logistics
email: contact@redshiftlogistics.online
url: https://redshiftlogistics.online/index.html
description: "Redshift Logistics is an independant corporation founded in 3270. We provide an array of services for clients whilst running our own operations."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#D5205E'

# Images
images:
  icon: 'https://cdn.discordapp.com/attachments/560450942554865666/598883706328842240/50fca4be-23d8-4ff9-809a-9e3b88ddc66e.png'
  header: 'https://cdn.discordapp.com/attachments/565682402878554112/588462328555765780/image1.png'
  logistics: ''
  mining: 'https://cdn.discordapp.com/attachments/565682402878554112/609875699767181354/IMG_b885bd5b-44e2-42c2-a298-081400d2424c.png'
  security: ''
  join-us: 'https://media.discordapp.net/attachments/565682402878554112/618507144475443210/IMG_38cbf46c-4b1f-4f44-bfb2-a1b5150a9098.png'
  about-us: ''
  contact-us: 'https://cdn.discordapp.com/attachments/565682402878554112/621139069417685015/share-external.png'

# Footer settings
footer: Redshift Logistics

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/rlog_elite
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
